apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: talker-api-trigger
spec:
  # filter:
  #   attributes:
  #     type: warehouse.order.v1
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: talker-api
    # uri: /custompath