# This is the main Kustomization file to deploy Authorino.
# It is the base of the deployment overlays in ./../overlays.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- oidc_service.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- auth_proxy_service.yaml
#- webhook
#- prometheus
#- scorecard

# Adds namespace to all resources.
namespace: authorino

# Value of this field is prepended to the names of all resources. E.g. a deployment named "controller" becomes "authorino-controller".
namePrefix: authorino-

# Labels to add to all resources and selectors.
commonLabels:
  app: authorino

patchesStrategicMerge:
- patches/manager_auth_proxy_patch.yaml
#- patches/manager_webhook_patch.yaml
#- patches/webhookcainjection_patch.yaml

images:
- name: authorino
  newName: quay.io/3scale/authorino
  newTag: latest

replicas:
- count: 1
  name: authorino-controller-manager
