apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- manage_cluster_role_binding.yaml
- auth_proxy_cluster_role_binding.yaml

# Adds namespace to all resources.
namespace: authorino
