# The following manifest contains a self-signed issuer CR
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager 1.4.0 check https://docs.cert-manager.io/en/latest/tasks/upgrading/index.html for breaking changes
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-cert
  namespace: system
spec:
  commonName: "*.$(AUTHORINO_NAMESPACE).svc"
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: authorino-ca-cert # this secret will not be prefixed, since it's not managed by kustomize
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: system
spec:
  ca:
    secretName: authorino-ca-cert
