apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config.authorino.3scale.net_services.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patchesStrategicMerge:
#- patches/webhook_in_services.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

#- patches/cainjection_in_services.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

patchesJson6902:
- path: patches/oneof_in_services.yaml
  target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: services.config.authorino.3scale.net

configurations:
- kustomizeconfig.yaml
