name: Build All
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      - name: Install JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 11
          architecture: x64

      - name: Checkout "${{ github.ref }}"
        uses: actions/checkout@v2

      - name: build
        run: |
          mvn install

      - name: Login to Quay
        run: |
          docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build
        run: |
          mvn install -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.group=famargon \
            -Dquarkus.container-image.tag=latest \
            -Dquarkus.container-image.registry=quay.io \
            -Dquarkus.container-image.push=true
        # -Dquarkus.container-image.push=true
        # -Dquarkus.container-image.name=custom-name
      
      - name: Build - mem component native
        run: |
          mvn install -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.group=famargon \
            -Dquarkus.container-image.tag=latest-native \
            -Dquarkus.container-image.registry=quay.io \
            -Dquarkus.container-image.push=true \
            -Dquarkus.native.container-build=true \
            -Dquarkus.package.type=native \
            -pl components/mem/

      - name: Build - kafka component native
        run: |
          mvn install -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.group=famargon \
            -Dquarkus.container-image.tag=latest-native \
            -Dquarkus.container-image.registry=quay.io \
            -Dquarkus.container-image.push=true \
            -Dquarkus.native.container-build=true \
            -Dquarkus.package.type=native \
            -pl components/kafka/

      - name: Images
        run: docker images | grep sharq